import '../scss/app.scss';
import '../img/logo.png';
import '../img/add.png';
import '../img/delete.png';
import '../img/edit.png';
import '../img/back3.gif'
import '../img/back4.jpg'
import '../img/modalback.jpg'
import '../img/evernote.png';
import '../img/facebook.png';
import '../img/google-plus.png';
import '../img/Instagram.png';
import 'bootstrap';
import 'jquery';
import 'jquery-ui';
import './navbar/view';
import './navbar/controller';
import './trelloboard/view';
import './trelloboard/controller';
import './boardlist/view';
import './boardlist/controller';
import './service';
